version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            make deps
      - run:
          command: |
            echo "build-$CIRCLE_BUILD_NUM" > VERSION
            make build
      - store_artifacts:
          path: /home/circleci/sigil/build
      - run:
          command: |
            make test
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
